---
abstract: 'RT AssetTracker-Asset-Dates Extension'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-AssetTracker-Asset-Dates
no_index:
  directory:
    - etc
    - html
    - inc
version: 0.009000
